name: pyth-bot
on:
  schedule:
    - cron: '*/5 * * * *' # co 5 min - stare alerty
    - cron: '0 5 * * *' # 5:00 UTC = 7:00 PL - podsumowanie
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests feedparser
      - name: Run normal alerts
        if: github.event.schedule!= '0 5 * * *'
        env:
          PHONE: ${{ secrets.PHONE }}
          APIKEY: ${{ secrets.APIKEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
      - name: Run daily summary 7:00 PL
        if: github.event.schedule == '0 5 * * *'
        env:
          PHONE: ${{ secrets.PHONE }}
          APIKEY: ${{ secrets.APIKEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SUMMARY: "1"
        run: python bot.py
